version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    command:
      - psql -U root -d planner -a -f ./schema.sql
    volumes:
      - ./schema.sql:/schema.sql
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
